export const HOME_FEATURED_BLOG_PREVIEWS = [
    {
        slug: 'how-to-get-first-1000-youtube-subscribers-2026',
        title: 'Як набрати перші 1000 підписників на YouTube у 2026 році: реальна система росту',
        excerpt: 'Покрокова стратегія для нового каналу: позиціонування, серії відео, Shorts, CTA та метрики, які приводять першу тисячу підписників.',
        coverImage: '/images/blog/youtube-channel-audit-checklist-2026.svg',
        coverAlt: 'Обкладинка статті про перші 1000 підписників на YouTube з графіком росту каналу',
        publishedAt: '7 березня 2026',
        publishedAtIso: '2026-03-07',
        readTime: '11 хв читання',
        tags: ['YouTube', 'Підписники', 'Зростання'],
    },
    {
        slug: 'why-youtube-subscribers-not-growing',
        title: 'Чому не ростуть підписники на YouTube: 15 причин, які гальмують канал',
        excerpt: 'Розбір типових причин слабкого росту: від неясної теми каналу до поганого утримання, слабких прев\'ю та хаотичної подачі.',
        coverImage: '/images/blog/community-posts-growth-system.svg',
        coverAlt: 'Обкладинка статті про причини, через які не ростуть підписники на YouTube',
        publishedAt: '7 березня 2026',
        publishedAtIso: '2026-03-07',
        readTime: '11 хв читання',
        tags: ['YouTube', 'Підписники', 'Аналітика'],
    },
    {
        slug: 'how-to-grow-youtube-channel-from-scratch-2026',
        title: 'Як розкрутити канал на YouTube з нуля: стратегія запуску без хаосу',
        excerpt: 'Практична стратегія старту каналу: як обрати нішу, оформити сторінку, спланувати перші відео і не зірвати запуск через хаос.',
        coverImage: '/images/blog/seo-keywords-for-youtube-channel-pages.svg',
        coverAlt: 'Обкладинка статті про розкрутку YouTube-каналу з нуля',
        publishedAt: '6 березня 2026',
        publishedAtIso: '2026-03-06',
        readTime: '11 хв читання',
        tags: ['YouTube', 'Зростання', 'Стратегія'],
    },
];
